# Generated by Django 5.1 on 2024-09-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0006_alter_comments_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogsapp.blog', to_field='bid'),
        ),
    ]
